sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=artifactory
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=artifactory
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/artifactory/Znw9qClIrIjFqXzYH-ZckGOS8Xc=
    - secure: MXWH3qnBcoDSZuBeRBTk2QRUNgkbPVjG6Bdrc0A/JLbAWHn9jo+6oWQDJNdSvZraNbHD7PpLbFBmrucTNdlsFuYhQXHe7T1QZ+sQWfsYwIx73DHwvtweQ5GFcCng6V8D7gdvcVLIKo4vYUy3fijryZ5aSLKnFJchTccDW9QS0wdzoK/lmjQ4R8Ik8AUn93/78GprD7lstM4rcrpyTiHtS15eU1p1rhpe5jN/6siD/OLXqGoDrF65C9BaT9lEjsdYpSn77DvoXylHLniurqh165WKahY1geCMz/mmWugLiDU4M7gewYXJ8aq8QqAYPOXghynmswjWYEpS8ILekfN/DPOAC1nkYrMpWFxxWyE5kL9KQIRFnNMqd/2oE4da6CX6CqvvfgWdEBMxPwjCUUW942GIQ+CAmNY2EDhQYWYsW1anAP6CaBtXFQ06WToEiJSMOXcfwWjM12PaRqFOpAxMTjbrAE3C9YEztJw0MuzrJi/YQouLW3L2wfaVmDHhyriQR+MGMuyzbhNRfUvtI8gvQE6v12AEXSPCS/G5m9uHUSiBM+iwcwKkyNTAx0NZTIml3ve5SxgvYwDgquM8z50g5wBkicYeqNx+YTXHisRDX6EyaffYKjyTYtvEvepqONurSYkGBl4fCFkifcAO4RY61YtAxhphREZfFYDEulfZzqc= # DOCKER_PASSWORD
    - secure: uge90v//+4d7GfQQYlCu4c1gnRgrRs2vhjW2/pL3CBEexNeQLCHRv99kRNQOnkZwvA0vTuuwcM7qJbWF1H8TBKnoyzVZbaouHLhfoGmFFXUrm1+t7sL17Rskr6bXJWoJYpR8KMTt6SJ+HB8oke6SHO7iGgIMUiT0SLau6I0+E5mS7oFJ/Zy+egbQI9l0hvSm99WJfLBo93KBsGIyuIOP9NyEI1uuUGOvluVqvEKorMWL3QIe9hawjnRXBDR2twZ+bGGoCsI3fDOGVEjOArNuzN0TTloJQAgvJpHx+nB7V3UOuEmyQqLIKHuED28zgpkL3UdfNEnY9ZC3RQfbr5hr5KsPGknmCieSlqkxaiZ83wc6ugK3E7N/lVqEXJdU4Z9jF5XB81EUIFz1uLZLIvyt7Hpv8kNNqBAH4kjGQ8wb1XdN0HdHBtXyzxxNXqIiY7rSI2r86Lsf38RK6kiE6ZtwQ1JXk9W81KXUFuYbLzLnWXF60FTR5VcaKEX8scy0j8fZPbIQ9Jc2vSmc/W5XOYJNfb6QVZQk2oCEJNuJ2UsSzj5QVPmiJ4OumCSdfQWSdAmvA9NmfIbTx+MQEW85aA3RB6wUTjChBXXhQzZveGCDxZ50rFWToUn2YRUrmdPeTemO6BIut1Subjw0juEAiK1tKltSvlA+htU5kDDSs5CyiPA= # QUAY_PASSWORD

install:
  - sudo apt-get update
  - docker --version

script:
  - bash build.sh
  - |
    test $TRAVIS_PULL_REQUEST = false \
    && echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin \
    && docker push $DOCKER_USERNAME/$DOCKER_REPONAME \
    && curl -X POST $MICROBADGER_HOOK \
    && echo "$QUAY_PASSWORD" | docker login quay.io --username "$QUAY_USERNAME" --password-stdin \
    && docker push quay.io/$DOCKER_USERNAME/$DOCKER_REPONAME

notifications:
  webhooks:
    secure: zgrMK4Fi0XNHU2rPinJcLexuMw+FpMET43Le3ijn7BcHO1f1ksJ7n1Jb8dHCyXVvUdwICNqslkdwFfcUtZn27SLT7oibdVUNE2gpNSOOm0gNU55RwcIqxtL/YGjN3LyinrOS+uVkR+15rSGea8jCmPL5f4bSbj7+2keuZ/UpjUyAda6TjvjaCBzZLPoxeWqJJyS31gyvkM7MTbyoum9m6zn+1PK1TYU5So4rFBWrZlWus96KhajoolVlYpsBpgTlYog8cn1AAlKF6jURv2pvpcuP69gjFtiT0MPdK4Zk9nLOKBn3Nrkc4l5NmRjJ7oXrfZJUdklwqUEdHsvo7DgkGhsbUFY0mn7zxYQZKskQyVSgzgykURI3Z0sXGlwzN2MYRsiDi7ncMzpYUqhK/Jg3hisMiyb5cpKyM5gn2qznPv4A9HDaiXbWH6zirT7uljtx09or8uByD9DWwOooiw3u1wVLPt/WUehq/z3p9i2yPdigzsYBoVciOb2sCQ+2IHDbf4fwtBh8K76fJU60l7jR+NYFx2KywBPSdS2UInsTWfkUnKjvEuSwVrP888HJiTh24sp1lpgrHMMgiaq6h3RDzobbjjhuJ7DUuwrEmFYwFaTvsfhrtJWjYRU4CTTmKVsUGmotUHd42A9OIHFRaaccJnSYXt5cHkwOtlXj9u18Zls=
