sudo: required

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=crazymax
    - DOCKER_REPONAME=artifactory
    - QUAY_USERNAME=crazymax
    - QUAY_REPONAME=artifactory
    - MICROBADGER_HOOK=https://hooks.microbadger.com/images/crazymax/artifactory/Znw9qClIrIjFqXzYH-ZckGOS8Xc=
    - secure: qTqfThCym4Ac+MEMImFj31rQujJKjajW9cty6B30PJA4jo8IwNi/TV0qJ4hvHc/ovWpxa3HQPM4lSQBrExNMtL3qaJisTQDFxYYfx+JT7dTwFhkKs7TCIIfZx6lW8Q2AuFXZuvrm7NcPIp66dLcC47yahy8DqGM6w2RjLfl+wLE+Y1O4KmW5DZYb+3YTd2aVAoBncte5tRV8jzgKU4iL8sPbkzm6wf00KMbifXCRfgfVuvT6PvICOD2bYedCtauyb+QG4G6qbEBePQIveUFOKsPUfcFINr9+SwRfzAwO2PoY5E4kNYk/dXHv9EkpR7Acq7xx+GKL9gdugdwYWORWWHxVdKTxq78GuHXmh6YzYM5oieSIrJzTTkOkJqp6LbCWRO1uJCpmDW3uEm98YllTcBP85WUv04hpvP2RHp+YffGwnWts+zM+9CmoV7nyMhzmW4SJr8BTQOF2z/6swH4/kGqMQY/mkOZKscVv4Nc/uQpMY0utLkm3OSZ1iu9LVpvjrxHpOMcyExqSynR4lecUvAY/BCxHRYUZsPlbytaS70HLIl01D8BlZe1x9ldrQ4tTy9fpzI75RF9THSSGkqWWZGG2LgaMTLFXz7EyTK40gTG3K2o2cjBttCIHdjuJnu13ajNyo33ysq9EmIQqdflAmuwkO+CqWrCdxIuuHtVvToY= # DOCKER_PASSWORD
    - secure: lp7QbQUz89B4KYIp0hg0Y6qMq5GFasKERWDLZaQp0HT6etVwptBXNwwTBMk4MzOMdJ/OR9qpjOgOL63NI/niRMvgCBbIag96KMKaGP23QRpsyE/zCgl2ErX6GD9OKURK9lA3Jauo4Af0LYrARRAwrs5H576te8kqALt2nfq8I6RVsqgSk/XhLLjDEDlYg4qffCe8dHVOvCzopQKKfdq3FW0qyLk3GqPjOPNI+3ve0q8cobkTzFYWfc79ijCDEuIoyhusxZRId1C2JfO3xl+dF6iB+xUG6ROs98HlA7tbCA6n6AjW1xXh9en//ztIkCsyBhWlZS8uftSoUVFU9Yb8XU1q/1h8rhDaarCkEq+R5WEM5HinxkPy6qAGPher/gBrNwZ/g6jJX/oLlRgugpx07M2xEz5yo15zOsP2eE3vmZeoW6GsYyCpjzKxnP33nEL+/oNLoif+EmOlTSsV12NlvTtHlQLCf2r2fuX6yek7jvhYnt0LuPqyL5R2pEsOjknPUAe1geNiXlygZ82na+27tAqlANOa6nHavh8ssXGlyZgD3boXHTVZUKfudFoPdGXHsI0DUasMqOoiy51AjTPhgsOh5QjqBLUiJc6ERAK+xgHVkLwhrhrraqTAR5ez7RHwXLwbH3TE4aGA7tp2qy2RPsT2nXxF729znog+pGE/j+M= # QUAY_PASSWORD

install:
  - sudo apt-get update
  - docker --version

script:
  - bash .travis/build.sh
  - test $TRAVIS_PULL_REQUEST = false && bash .travis/push.sh

notifications:
  email:
    - akqmpo75h0r3@abinemail.com
