name: build

on:
  push:
    branches: 'master'
    paths:
      - '.github/workflows/build.yml'
      - 'images/**'

env:
  DOCKER_IMAGE: crazymax/artifactory

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Get Docker JWT Token
        id: jwt
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ env.DOCKER_IMAGE }}:pull" | jq -r .token)
          if [ -z ${TOKEN} -o ${TOKEN} == "null" ]; then
            echo "::error::Cannot retrieve token"
            exit 1
          fi
          echo ::set-output name=token::${TOKEN}
      -
        name: Get Docker Tags
        id: tags
        if: success()
        run: |
          TAG_LIST=$(curl -s -H "Authorization: Bearer ${{ steps.jwt.outputs.token }}" "https://index.docker.io/v2/${{ env.DOCKER_IMAGE }}/tags/list" | jq -rc '.tags[]')
          echo ::set-output name=list::${TAG_LIST}
      -
        name: Docker Pull
        if: success()
        run: |
          function docker_pull() {
            echo "📥 Pulling Artifactory $2 $3 from $1..."
            for TAG in $(echo ${{ steps.tags.outputs.list }} | sed "s/,/ /g"); do
              if [ "$3" != "latest" ] && [ "$TAG" = "$2-$3" ]; then
                echo "🔫 Tag $2-$3 already exists and is not latest... Skipping..."
                return
              fi
            done
            docker pull $1:$3
            docker tag $1:$3 ${{ env.DOCKER_IMAGE }}:$2-$3
          }

          # Artifactory oss
          while IFS= read -r version
          do
            docker_pull "docker.bintray.io/jfrog/artifactory-oss" "oss" "$version"
          done < "./images/artifactory-oss.txt"

          # Artifactory pro
          while IFS= read -r version
          do
            docker_pull "docker.bintray.io/jfrog/artifactory-pro" "pro" "$version"
          done < "./images/artifactory-pro.txt"

          # Nginx Artifactory pro
          while IFS= read -r version
          do
            docker_pull "docker.bintray.io/jfrog/nginx-artifactory-pro" "nginx-pro" "$version"
          done < "./images/nginx-artifactory-pro.txt"

          # Postgres
          while IFS= read -r version
          do
            docker_pull "jfrog-docker-reg2.bintray.io/postgres" "postgres" "$version"
          done < "./images/postgres.txt"
      -
        name: Login to DockerHub
        if: success()
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Docker Push
        if: success()
        run: |
          docker push ${{ env.DOCKER_IMAGE }}
